language: python
python:
- '3.6'
cache:
  directories:
  - "$HOME/google-cloud-sdk"
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - PROJECT_NAME=supple-bank-232805
  - CLUSTER_NAME=bigmood-trends-sentiment-testing
  - CLOUDSDK_COMPUTE_ZONE=us-central1-c
before_install:
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet version
- gcloud --quiet components update
- gcloud --quiet components update beta
- gcloud --quiet components update kubectl
- echo $super_secret_password | gpg --passphrase-fd 0 My-project-key.json.gpg
- echo $super_secret_password | gpg --passphrase-fd 0 conf.py.gpg
- mv conf.py ./config/

install:
- pip install -r ./requirements.txt
- docker
script:
- echo "success installing."
- pwd
- ls -l

before_deploy:
- gcloud --quiet components update kubectl
deploy:
- provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
